# Generated by Django 5.1.2 on 2024-12-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter your full name', max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=254, unique=True, verbose_name='Email Address')),
            ],
        ),
    ]
