# Generated by Django 5.1.2 on 2024-12-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='username',
        ),
    ]
